---
name: Actions tester

on:
#  push:
#    branches: [ master ]
#    paths-ignore:
#      - '.circleci/'
#      - '.gitignore'
#      - 'CODEOWNERS'
#      - 'README.md'
  push:
    paths:
    - 'mac/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Validate step is run
        run: echo 'File/s changed!!'
