---
name: Actions main

on:
#  push:
#    branches: [ master ]
#    paths-ignore:
#      - '.circleci/'
#      - '.gitignore'
#      - 'CODEOWNERS'
#      - 'README.md'
  push:
    paths:
    - 'mac/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-1:
    # The type of runner that the job will run on
    runs-on: g6

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: sleep
        run: sleep 10
        
      - name: Validate step is run
        run: echo 'File/s changed!!'
        
  build-2:
    # The type of runner that the job will run on
    runs-on: g6

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: another sleep
        run: sleep 5
        
      - name: just another job
        run: echo 'Second job'
