name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      operation_type:
        description: "Operation type to add or delete a runner. Valid values are: 'add' or 'remove'"
        default: add
        required: true
      token:
        description: 'A GitHub actions runner token'
        required: true
      vm_name:
        description: "If the 'Operation Type' is 'remove', the runner VM Name must be provided!"
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.operation_type }}!"
        echo "- in ${{ github.event.inputs.token }}!"
        echo "- in ${{ github.event.inputs.vm_name }}!"
