---
name: Actions new

on:
  push:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:     
  build-new:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: A new job
        id: step_1
        run: |
          output=$(echo 'Actions new job')
          echo $output
          echo "::set-output name=output::$output"
        
      - name: sleep step
        run: echo ${{ steps.step_1.outputs }}
